name: Python Script Workflow

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-python:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_ID: "@astanafeels"

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Show environment variables (safe ones)
      run: |
        echo "CHANNEL_ID=$CHANNEL_ID"
        echo "Python version:"
        python --version

    - name: List files in workspace
      run: |
        pwd
        ls -alh

    - name: Install dependencies
      run: |
        set -x  # Enables command tracing
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  

    - name: Run Python script with debug output
      run: |
        set -x
        python meteo.py